feat(ci/cd): publish action
newrelic/nri-nagios pull request #30
Opened 2021-03-22 16:40 UTC by paologallinaharbur

Fix https://github.com/newrelic/nri-nagios/issues/28
Adds support for publishing action to S3 and test action for repositories

2021-03-23 11:56 UTC, gsanchezgavier approved these changes

2021-03-25 09:39 UTC, gsanchezgavier requested changes
just checked that win-config needs to be removed here too

2021-03-25 11:44 UTC, paologallinaharbur commented
I'll add that, thanks for noticing!

2021-03-25 11:59 UTC, gsanchezgavier approved these changes
lgtm

2021-03-25 13:42 UTC, merged